routes/categoria.py
from flask import Blueprint, render_template, request, redirect, url_for, flash,session
from sqlalchemy import text
from utils.db import db
from werkzeug.security import generate_password_hash, check_password_hash
from utils.helper import login_required

categoria = Blueprint("categoria", __name__)


@categoria.route('/categoria')
@login_required
def index():
    id=  session['usuario_id']
    usuarios = db.session.execute(text("SELECT * FROM usuarios WHERE id = :id"),
            {"id": id}
        ).fetchone()
    categoria = db.session.execute(
            text("SELECT * FROM categoria")
        ).fetchall()
    notificaciones = db.session.execute(
        text("""
            SELECT id, descripcion, medio, visto 
            FROM notificacion 
            WHERE usuario_id = :usuario_id 
           
        """),
        {"usuario_id": id}
    ).fetchall()
    return render_template('categoria/index.html',categoria=categoria,usuarios=usuarios,notificaciones=notificaciones)

@categoria.route('/crearcategoria',methods=["POST", "GET"])
@login_required
def categoriacrear():
    
     if request.method == 'POST':
        # Capturar datos del formulario
        nombre = request.form['nombre']
      
        descripcion = request.form['descripcion']
        tipo= request.form['habitual']
        # Verificar si la categoria ya existe por el nombre
        existente = db.session.execute(
            text("SELECT * FROM categoria WHERE nombre = :nombre"),
            {"nombre": nombre}
        ).fetchone()

        if existente:
            flash(
                "El nombre y la categoria ya estan registrados. Intente con otros datos.", "error")
            return redirect(url_for('categoria.index'))

        # Insertar el nuevo usuario en la base de datos
        db.session.execute(
            text("INSERT INTO categoria (nombre, descripcion,tipo) VALUES (:nombre, :descripcion,:tipo)"),
            {"nombre": nombre, 
                "descripcion": descripcion,
                    "tipo": tipo}
        )
        db.session.commit()  # Confirmar cambios en la base de datos
        flash("Registro exitoso. .", "success")
        return redirect( url_for('categoria.index') )
    

@categoria.route('/actualizarcategoria/<int:id>', methods=["POST", "GET"])
@login_required
def actualizar_categoria(id):
    # Recuperamos el egreso que vamos a editar
    categoria = db.session.execute(
        text("SELECT * FROM categoria WHERE id = :id"),
        {"id": id}
    ).fetchone()

    if not categoria:
        flash("Categoria no encontrado.", "error")
        return redirect(url_for('categoria.index'))

    if request.method == 'POST':
        # Capturamos los datos enviados en el formulario
        nombre= request.form['nombre']
        descripcion = request.form['descripcion']
        
        # Validación de los campos
        
        
        db.session.execute(
            text("""
                UPDATE categoria
                SET nombre= :nombre, descripcion= :descripcion 
                WHERE id = :id
            """),
            {
                "nombre": nombre,
                "descripcion": descripcion,
                "id": id
            }
        )
        db.session.commit()  

        flash("Categoria actualizada exitosamente.", "success")
        return redirect(url_for('categoria.index'))


@categoria.route('/marcar_como_vista/<int:notificacion_id>', methods=['POST'])
def marcar_como_vista(notificacion_id):
    # Verificar que el usuario esté autenticado
    usuario_id = session.get('usuario_id')
    if not usuario_id:
        return redirect(url_for('login'))  # Redirige si no está autenticado

    # Actualizar la notificación como vista
    db.session.execute(
        text("""
            UPDATE notificacion
            SET visto = 1
            WHERE id = :notificacion_id AND usuario_id = :usuario_id
        """),
        {"notificacion_id": notificacion_id, "usuario_id": usuario_id}
    )
    db.session.commit()
    flash("Registro exitoso. .", "success")

    # Redirigir de nuevo a la página de notificaciones
    return redirect(url_for('categoria.index'))

routes/registro.py
from flask import Blueprint, render_template, request, redirect, url_for, flash, session
from sqlalchemy import text
from utils.db import db
from werkzeug.security import generate_password_hash, check_password_hash
from utils.helper import login_required

usuarios = Blueprint("usuarios", __name__)


@usuarios.route('/usuarios')
@login_required
def index():
    usuarios = db.session.execute(text("SELECT * FROM usuarios")).fetchall()

    return render_template('index.html', usuarios=usuarios)

@usuarios.route('/perfil')
@login_required
def perfil():
    id=  session['usuario_id']
    usuarios = db.session.execute(text("SELECT * FROM usuarios WHERE id = :id"),
            {"id": id}
        ).fetchone()
    print(usuarios)

    return render_template('Layout/perfil.html',usuarios=usuarios)


@usuarios.route('/actualizar_perfil', methods=['POST'])
@login_required
def actualizar_perfil():
    usuario_id = session['usuario_id']
    nombre = request.form['nombre']
    correo = request.form['correo']
    telefono = request.form['telefono']
    
    # Verificar si el correo o teléfono ya existen en otros usuarios
    existente = db.session.execute(
        text("SELECT * FROM usuarios WHERE (correo = :correo OR telefono = :telefono) AND id != :id"),
        {"correo": correo, "telefono": telefono, "id": usuario_id}
    ).fetchone()
   

    # Si existe un usuario con el mismo correo o teléfono
    if existente:
        flash("El correo o teléfono ya están registrados por otro usuario.", "error")
        return redirect(url_for('categoria.index'))

    # Realizar la actualización si no existe ningún conflicto
    db.session.execute(
        text("UPDATE usuarios SET nombre = :nombre, correo = :correo, telefono = :telefono WHERE id = :id"),
        {"nombre": nombre, "correo": correo, "telefono": telefono, "id": usuario_id}
    )
    db.session.commit()

    flash("Perfil actualizado exitosamente.", "success")
    return redirect(url_for('categoria.index'))

@usuarios.route('/auth/login', methods=['GET', 'POST'])
def login():
    if request.method == 'POST':
        # Capturar datos del formulario
        correo = request.form['correo']
        clave = request.form['clave']

        # Verificar si el usuario existe en la base de datos
        usuario = db.session.execute(
            text("SELECT * FROM usuarios WHERE correo = :correo"),
            {"correo": correo}
        ).fetchone()
        print(usuario)
        # Si el usuario existe y la contraseña coincide
        if usuario and check_password_hash(usuario[4], clave):
            # Iniciar sesión guardando datos en la sesión del usuario
            session['usuario_id'] = usuario[0]
            session['nombre'] = usuario[1]
            session['correo']=usuario[4]
            flash("Inicio de sesión exitoso. Bienvenido/a, " +
                  usuario[1], "success")
            return redirect(url_for('transacciones.index'))
        else:
            flash("Correo o contraseña incorrectos.", "error")
            return redirect(url_for('usuarios.login'))

    # Si es un método GET, renderizar el formulario de login
    return render_template('Login/login.html')


@usuarios.route('/auth/registro', methods=['GET', 'POST'])
def registro():
    if request.method == 'POST':
        # Capturar datos del formulario
        nombre = request.form['nombre']
        telefono = request.form['telefono']
        correo = request.form['correo']
        clave = request.form['clave']
        hash = generate_password_hash(clave)

        # Verificar si el usuario ya existe por correo o teléfono
        existente = db.session.execute(
            text("SELECT * FROM usuarios WHERE correo = :correo OR telefono = :telefono"),
            {"correo": correo, "telefono": telefono}
        ).fetchone()

        if existente:
            flash(
                "El correo o teléfono ya están registrados. Intente con otros datos.", "error")
            return redirect(url_for('usuarios.registro'))

        # Insertar el nuevo usuario en la base de datos
        db.session.execute(
            text("INSERT INTO usuarios (nombre, telefono, correo, clave) VALUES (:nombre, :telefono, :correo, :clave)"),
            {"nombre": nombre, "telefono": telefono,
                "correo": correo, "clave": hash}
        )
        db.session.commit()  # Confirmar cambios en la base de datos
        flash("Registro exitoso. Ahora puedes iniciar sesión.", "success")
        return redirect(url_for('usuarios.index'))

    # Si es un método GET, renderizar el formulario de registro
    return render_template('Login/registro.html')


@usuarios.route("/logout", methods=["POST", "GET"])
def logout():

    session.pop('usuario_id', None)
    # Redireccionar al inicio de sesión
    flash("Se ha cerrado la sesion correctamente", "success")
    return redirect(url_for('usuarios.login'))

templates/Categoria/index.html
{% extends "Layout/base.html" %}

{% block title %}Configuraciones - FinanzApp{% endblock %}
<style>
  .card {
    border-radius: 15px;
    transition: all 0.3s ease;
  }

  .card:hover {
    box-shadow: 0 0.5rem 1rem rgba(0, 0, 0, 0.15) !important;
  }

  .list-group-item {
    transition: background-color 0.3s ease;
  }

  .list-group-item:hover {
    background-color: #f8f9fa;
  }

  .btn {
    border-radius: 25px;
    padding: 10px 20px;
  }
</style>
{% block content %}
<div class="d-flex align-items-start">
  <div class="nav flex-column nav-pills me-3" id="v-pills-tab" role="tablist" aria-orientation="vertical">
    <button class="nav-link iconos-financieros active" id="v-pills-home-tab" data-bs-toggle="pill"
      data-bs-target="#v-pills-home" type="button" role="tab" aria-controls="v-pills-home"
      aria-selected="true">Categorias</button>
    <button class="nav-link" id="v-pills-profile-tab" data-bs-toggle="pill" data-bs-target="#v-pills-profile"
      type="button" role="tab" aria-controls="v-pills-profile" aria-selected="false">Perfil</button>

    <button class="nav-link" id="v-pills-messages-tab" data-bs-toggle="pill" data-bs-target="#v-pills-messages"
      type="button" role="tab" aria-controls="v-pills-messages" aria-selected="false">Messages</button>

  </div>
  <div class="tab-content" id="v-pills-tabContent">
    <div class="tab-pane fade show active" id="v-pills-home" role="tabpanel" aria-labelledby="v-pills-home-tab"
      tabindex="0">

      <div class="d-flex justify-content-end mb-3">
        <button type="button" class="btn btn-success" data-bs-toggle="modal" data-bs-target="#exampleModal">
          <i class="bi bi-plus-circle me-2"></i>
          Registrar Categoria
        </button>
      </div>
      <!-- Modal -->
      <div class="modal fade" id="exampleModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
        <div class="modal-dialog">
          <div class="modal-content">
            <div class="modal-header">
              <h1 class="modal-title fs-5" id="exampleModalLabel">Nueva categoria</h1>
              <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <form action="/crearcategoria" method="post">
              <div class="modal-body">

                <div class="mb-3">
                  <label for="description" class="form-label">Nombre</label>
                  <input type="text" class="form-control" id="nombre" name="nombre" required="">
                </div>
                <div class="mb-3">
                  <label for="description" class="form-label">Descripción</label>
                  <input type="text" class="form-control" id="description" name="descripcion" required="">
                </div>
                <div class="col-12">
                  <label class="form-label">¿De que tipo?</label>
                  <div class="form-check">
                    <input class="form-check-input" type="radio" name="habitual" id="habitual_si" value="1" required>
                    <label class="form-check-label" for="habitual_si">
                      Ingresos
                    </label>
                  </div>
                  <div class="form-check">
                    <input class="form-check-input" type="radio" name="habitual" id="habitual_no" value="0" required>
                    <label class="form-check-label" for="habitual_no">
                      Egresos
                    </label>
                  </div>
                </div>
              </div>




              <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Cerrar</button>
                <button type="submit" class="btn btn-success">Agregar</button>
              </div>
            </form>
          </div>
        </div>
      </div>
      <div class="container-fluid">
        <div class="table-responsive">
          <table class="table table-striped table-success dataTable" id="dataTable">
            <thead>
              <tr>
                <th scope="col">#</th>
                <th scope="col">Nombre</th>
                <th scope="col">Descripción</th>
                <th scope="col">Acciones</th>
              </tr>
            </thead>
            <tbody>
              {% for categoria in categoria %}
              <tr>
                <th scope="row">{{categoria.id}}</th>
                <td>{{categoria.nombre}}</td>
                <td>{{categoria.descripcion}}</td>
                <td>
                  <a class="btn btn-success" data-bs-toggle="modal" data-bs-target="#modal-default{{categoria.id}}">
                    <i class="fas fa-pencil-alt"></i> Editar
                  </a>
                </td>
              </tr>
              {% endfor %}


            </tbody>
          </table>
        </div>
      </div>
      {% for categoria in categoria %}
      <div class="modal fade" id="modal-default{{categoria.id}}" tabindex="-1" aria-labelledby="exampleModalLabel"
        aria-hidden="true">
        <div class="modal-dialog">
          <div class="modal-content">
            <div class="modal-header">
              <h1 class="modal-title fs-5" id="exampleModalLabel">Editar categoria</h1>
              <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <form action="/actualizarcategoria/{{categoria.id}}" method="post">
              <div class="modal-body">
                <!-- Campo Divisa -->

                <!-- Campo Cantidad -->
                <div class="row mb-3">
                  <div class="col-12">
                    <label for="cantidad" class="form-label">Nombre</label>
                    <input type="text" class="form-control" id="nombre" name="nombre" value="{{categoria.nombre}}"
                      required min="1">
                  </div>
                </div>
                <div class="row mb-3">
                  <div class="col-12">
                    <label for="descripcion" class="form-label">Descripcion</label>
                    <input type="text" class="form-control" id="descripcion" name="descripcion"
                      value="{{categoria.descripcion}}" required min="1">
                  </div>
                </div>


              </div>
              <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Cerrar</button>
                <button type="submit" class="btn btn-primary">Actualizar</button>
              </div>
            </form>
          </div>
        </div>
      </div>
      {% endfor %}
    </div>
    <div class="tab-pane fade" id="v-pills-profile" role="tabpanel" aria-labelledby="v-pills-profile-tab" tabindex="0">
      <div class="container py-5">
        <div class="row justify-content-center">
          <div class="col-md-12">
            <div class="card shadow-sm">
              <div class="card-body">
                <div class="text-center mb-4">
                  <img src="https://api.dicebear.com/6.x/initials/svg?seed={{ usuarios['nombre'] }}"
                    alt="{{ usuarios['nombre'] }}" class="rounded-circle mb-3" width="100" height="100">
                  <h2 class="card-title">{{ usuarios['nombre'] }}</h2>
                </div>
                <ul class="list-group list-group-flush mb-4">
                  <li class="list-group-item d-flex justify-content-between align-items-center">
                    <span><i class="bi bi-person-fill me-2 text-primary"></i><strong>Nombre:</strong></span>
                    <span>{{ usuarios['nombre'] }}</span>
                  </li>
                  <li class="list-group-item d-flex justify-content-between align-items-center">
                    <span><i class="bi bi-envelope-fill me-2 text-primary"></i><strong>Correo:</strong></span>
                    <span>{{ usuarios['correo'] }}</span>
                  </li>
                  <li class="list-group-item d-flex justify-content-between align-items-center">
                    <span><i class="bi bi-telephone-fill me-2 text-primary"></i><strong>Teléfono:</strong></span>
                    <span>{{ usuarios['telefono'] }}</span>
                  </li>
                </ul>
                <div class="d-grid gap-2">
                  <button type="button" class="btn btn-primary mt-3" data-bs-toggle="modal"
                    data-bs-target="#actualizarModal">
                    <i class="bi bi-pencil-square me-2"></i> Actualizar
                  </button>
                  <a href="{{ url_for('usuarios.logout') }}" class="btn btn-outline-danger">
                    <i class="bi bi-box-arrow-right me-2"></i>Cerrar sesión
                  </a>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>

      <!-- Modal -->
      <div class="modal fade" id="actualizarModal" tabindex="-1" aria-labelledby="actualizarModalLabel"
        aria-hidden="true">
        <div class="modal-dialog">
          <div class="modal-content">
            <div class="modal-header">
              <h5 class="modal-title" id="actualizarModalLabel">Actualizar Perfil</h5>
              <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <form action="{{ url_for('usuarios.actualizar_perfil') }}" method="POST">
              <div class="modal-body">
                <div class="mb-3">
                  <label for="nombre" class="form-label">Nombre</label>
                  <input type="text" class="form-control" id="nombre" name="nombre" value="{{ usuarios['nombre'] }}">
                </div>
                <div class="mb-3">
                  <label for="correo" class="form-label">Correo</label>
                  <input type="email" class="form-control" id="correo" name="correo" value="{{ usuarios['correo'] }}">
                </div>
                <div class="mb-3">
                  <label for="telefono" class="form-label">Teléfono</label>
                  <input type="text" class="form-control" id="telefono" name="telefono"
                    value="{{ usuarios['telefono'] }}">
                </div>
              </div>
              <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Cancelar</button>
                <button type="submit" class="btn btn-success">Guardar cambios</button>
              </div>
            </form>
          </div>
        </div>
      </div>

    </div>

    <div class="tab-pane fade" id="v-pills-messages" role="tabpanel" aria-labelledby="v-pills-messages-tab"
      tabindex="0">
      <h1>Notificaciones</h1>
      {% if notificaciones %}
      <ul class="list-group">
        {% for notificacion in notificaciones %}
        <li class="list-group-item {{ 'bg-light' if notificacion.visto == 0 else '' }}">
          <div>
            <strong>{{ notificacion.descripcion }}</strong>
            <br>
            <p><i>{{ notificacion.medio }}</i></p>
            {% if notificacion.visto == 0 %}
            <span class="badge bg-danger">No vista</span>
            <form action="{{ url_for('categoria.marcar_como_vista', notificacion_id=notificacion.id) }}" method="post">
              <button type="submit" class="btn btn-sm btn-success">Marcar como leída</button>
          </form>
          
            {% else %}
            <span class="badge bg-success">Vista</span>
            {% endif %}
          
          </div>
        </li>
        {% endfor %}
      </ul>
      {% else %}
      <p class="text-muted">No tienes notificaciones.</p>
      {% endif %}
    </div>

  </div>
</div>
<!-- Button trigger modal -->

{% endblock %}